title: Road to FullStack Web Dev
author: @matiasbernal
email: matiasa.bernal@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 
 Hello readers, follow me in my way to **learn** fullstack web dev and how to get work in 6 months after learn.

# social links
instagram_username: _matiasbernal # DO NOT include the @ character, or else the build will fail!
github_username:  matiasbernal # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
